# Copyright (c) 2017-2020 Dell Inc.
# Copyright (c) 2022 Andreas Florath, Deutsche Telekom AG
---
galaxy_info:
  author: Dell EMC Networking Engineering
  description: The os10_ptp role facilitates the configuration of PTP clock and interfaces running Dell EMC SmartFabric OS10.
  company: Dell Technologies
  license: GPLv3
  min_ansible_version: 2.9.6

  platforms:
  - name: os10

  galaxy_tags:
    - networking
    - dell
    - emc
    - dellemc
    - os10
